<?php
// @see https://github.com/fabiopaiva/zf2-navigation-bootstrap3
// Updated for Bootstrap 5
/* @var $container Zend\Navigation\Navigation */
$container = $this->container;
$ulClass= 'navbar-nav me-auto mb-2 mb-md-0';
?>
<!-- view/common/bootstrap-navigation.phtml -->
<ul class="<?php echo $ulClass; ?>">
    <?php foreach ($container as $page): ?>
        <?php if (!$this->navigation()->accept($page)) continue; ?>
        <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
        <?php $hasChildren = $page->hasPages() ?>
        <?php if (!$hasChildren): ?>
            <li class="nav-item">
                <a
                    class="nav-link<?php if ($page->isActive()) echo ' active' ?>"
                    href="<?php echo $page->getHref() ?>"
                    <?php if ($page->getTarget() != ""): ?>
                        target="<?php echo $page->getTarget(); ?>"
                    <?php endif; ?>
                    >
                    <?php echo $this->escapeHtml($this->translate($page->getLabel(), $this->navigation($container)->getTranslatorTextDomain())); ?>
                </a>
            </li>
        <?php else: ?>
            <?php
            //check if access is allowed at least one item
            $access = false;
            foreach ($page->getPages() as $child) {
                if ($this->navigation()->accept($child) && $child->get("separator") !== true) {
                    $access = true;
                }
            }
            if ($access) :
                ?>
                <li class="nav-item dropdown<?php if ($page->isActive(true)) echo ' active' ?>">
                    <a id="dropdown" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" href="#">
                        <?php echo $this->escapeHtml($this->translate($page->getLabel(),$this->navigation($container)->getTranslatorTextDomain())); ?>
                    </a>
                    <ul class="dropdown-menu" aria-controlledby="dropdown">
                        <?php foreach ($page->getPages() as $child): ?>
                            <?php if (!$this->navigation()->accept($child)) continue; ?>
                            <?php if ($child->get("separator") === true): ?>
                                <li class="divider"></li>
                                    <?php
                                    continue;
                                endif;
                                ?>
                            <li<?php if ($child->isActive()) echo ' class="active"' ?>>
                                <a class="dropdown-item"
                                    href="<?php echo $child->getHref() ?>"
                                    <?php if ($child->getTarget() != ""): ?>
                                        target="<?php echo $child->getTarget(); ?>"
                                    <?php endif; ?> >
                                        <?php if ($child->get("icon") !== ""): ?>
                                        <span class="<?php echo $child->get("icon"); ?>"></span>
                                    <?php endif; ?>
                                    <?php echo $this->escapeHtml($this->translate($child->getLabel(),$this->navigation($container)->getTranslatorTextDomain())); ?>
                                </a>
                            </li>
                        <?php endforeach ?>
                    </ul>
                </li>
            <?php endif; ?>
        <?php endif ?>
    <?php endforeach ?>

    <li><?php echo $this->partial('common/search-form'); ?></li>
</ul>
