
<?php
$translate = $this->plugin('translate');
?>

<div class="container" style="">
  <!-- <nav class="pagination" role="navigation" aria-label="Item Navigation"> -->
    <?php if ($totalCount): ?>
      <ul class="nav">
        <li class="nav-item">
          <form method="GET" action="">
              <?php echo $this->queryToHiddenInputs(['page']); ?>
              <input type="text" name="page" class="form-control" value="<?php echo $currentPage; ?>" size="4" <?php echo ($pageCount == 1) ? 'readonly' : ''; ?> aria-label="<?php echo $translate('Page'); ?>">
              <span class="mr-5"><?php echo sprintf($translate('of %s'), $pageCount); ?></span>
          </form>
        </li>
        <?php if ($currentPage != 1): ?>
          <li class="nav-item">
            <?php echo $this->hyperlink('Previous', $previousPageUrl, ['class' => 'page-link', 'title' => $translate('Previous'), 'aria-label' => $translate('Previous')]); ?>
          </li>
        <?php else: ?>
            <li class="page-item disabled">
              <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
            </li>
        <?php endif; ?>

        <?php if ($currentPage < $pageCount): ?>
          <li class="page-item">
            <?php echo $this->hyperlink('Next', $nextPageUrl, ['class' => 'page-link', 'title' => $translate('Next'), 'aria-label' => $translate('Next')]); ?>
          </li>
        <?php else: ?>
          <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
        <?php endif; ?>

        <li class="nav-item">
          <?php
          $from = $offset + 1;
          $to = ($currentPage < $pageCount) ? $offset + $perPage : $totalCount;
          ?>
          <span class="row-count mt-2 mb-5">
            <?php echo sprintf($translate('%1$s–%2$s of %3$s'), $from, $to, $totalCount); ?>
          </span>
        </li>
      </ul>

    <?php else: ?>
        <?php echo $translate('0 results'); ?>
    <?php endif; ?>
  <!-- </nav> -->
</div>
