<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$labelInfo = $this->setting('property_label_information');
?>

<?php //var_dump($values); ?>

<dl class="row">
<?php foreach($values as $term => $propertyData): ?>
  <dt class="col-sm-3 term">
    <?php if($propertyData['alternate_label']): ?>
      <?php echo $escape($propertyData['alternate_label']); ?>
      one
    <?php else: ?>
      <?php echo $escape($translate($propertyData['property']->label())); ?>
      <code>
          <?php var_dump($term); ?>
      </code>
    <?php endif; ?>
    <?php if ('term' === $labelInfo): ?>
      (<?php echo $escape($propertyData['property']->term()); ?>)
    <?php elseif ('vocab' === $labelInfo): ?>
      (<?php echo $escape($propertyData['property']->vocabulary()->label()); ?>)
    <?php endif; ?>
  </dt>
  <dd class="col-sm-9">
     <?php foreach ($propertyData['values'] as $value): ?>
       <?php
        $valueType = $value->type();
        $class=['value'];
        if ('resource' == $valueType || strpos($valueType, 'resource') !== false) {
                $class[] = 'resource';
                $class[] = $escape($value->valueResource()->resourceName());
            } elseif ('uri' == $valueType) {
                $class[] = 'uri';
            }
            if (!$value->isPublic()) {
                $class[] = 'private';
            }
        ?>

        <div class="<?php echo implode(' ', $class); ?>" lang="<?php echo $escape($value->lang()); ?>">
                <?php if ($language = $value->lang()): ?>
                <span class="language"><?php echo $language; ?></span>
                <?php endif; ?>
                <?php echo $value->asHtml(); ?>
            </div>
     <?php endforeach; ?>
  </dd>
<?php endforeach; ?>
</dl>
