<?php
$translate = $this->plugin('translate');
$searchType = $this->siteSetting('search_type', 'sitewide');
switch ($searchType) {
    case 'cross-site':
        $searchAction = $this->url('site/cross-site-search', ['action' => 'results'], true);
        break;
    case 'sitewide':
    default:
        $searchAction = $this->url('site/resource', ['controller' => 'index', 'action' => 'search'], true);
}
$searchValue = $this->escapeHtml($this->params()->fromQuery('fulltext_search', ''));
  // $search = $this->escapeHtml($this->url(null, ['action' => 'browse'], true));
  $search = $this->escapeHtml($searchAction);
?>

<!-- view/common/search-form.phtml -->
<form action="<?php echo $search ?>" id="search-form" class="input-group">
    <input class="form-control" type="text" name="fulltext_search" value="<?php echo $searchValue; ?>"
        placeholder="<?php echo $translate('Search'); ?>"
        aria-label="<?php echo $translate('Search'); ?>" class="form-text input-group-field">
    <div class="input-group-button">
    <button type="submit" class="btn btn-primary"><?php echo $translate('Search'); ?></button>
    </div>
</form>
