<?php
$translate = $this->plugin('translate');
$searchType = $this->siteSetting('search_type', 'sitewide');
switch ($searchType) {
    case 'cross-site':
        $searchAction = $this->url('site/cross-site-search', ['action' => 'results'], true);
        break;
    case 'sitewide':
    default:
        $searchAction = $this->url('site/resource', ['controller' => 'index', 'action' => 'search'], true);
        // $searchAction = $this->url('site/resource', ['controller' => 'item'], true);
}
$searchValue = $this->escapeHtml($this->params()->fromQuery('fulltext_search', ''));
  // http://localhost:8888/omeka-s/s/iraqi-jewish-archive/index/search?fulltext_search=book
  // http://localhost:8888/omeka-s/s/iraqi-jewish-archive/item?fulltext_search=book

  // $search = $this->escapeHtml($this->url(null, ['action' => 'browse'], true));
  $search = $this->escapeHtml($searchAction);
?>

<!-- view/common/search-form.phtml -->
<form action="<?php echo $search ?>" id="search-form" class="d-flex">
  <div class="input-group">
    <div class="form-outline">
      <input class="form-control me-2" type="text" name="fulltext_search" value="<?php echo $searchValue; ?>"
          placeholder="<?php echo $translate('Search'); ?>"
          aria-label="<?php echo $translate('Search'); ?>" class="form-text input-group-field">
    </div>
    <button type="submit" class="btn btn-primary">
      <i class="fas fa-search"></i>
      <span class="visually-hidden"><?php echo $translate('Search'); ?></span>
    </button>
  </div>
</form>