<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
?>
<!-- view/common/sort-selector.phtml -->
<form class="sorting" action="">
  <div class="form-row row">
    <div class="col">
      <?php echo $this->queryToHiddenInputs(['sort_by', 'sort_order']); ?>
      <select class="form-select" name="sort_by" aria-label="<?php echo $translate('Sort by'); ?>">
      <?php foreach($sortBy as $sortByHeading): ?>
          <?php $selected = ($sortByQuery === $sortByHeading['value']) ? 'selected' : ''; ?>
          <option value="<?php echo $escape($sortByHeading['value']); ?>" <?php echo $selected; ?>><?php echo $sortByHeading['label']; ?></option>
      <?php endforeach; ?>
      </select>
    </div>
    <div class="col">
      <select class="form-select" name="sort_order" aria-label="<?php echo $translate('Sort order'); ?>">
          <option value="asc" <?php echo ($sortOrderQuery === 'asc') ? 'selected' : ''; ?>><?php echo $translate('Ascending'); ?></option>
          <option value="desc" <?php echo ($sortOrderQuery === 'desc') ? 'selected' : ''; ?>><?php echo $translate('Descending'); ?></option>
      </select>
    </div>

    <div class="col">
      <button class="btn btn-primary" type="submit"><?php echo $translate('Sort'); ?></button>
    </div>

  </div>
</form>
