<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
// $this->headScript()->appendFile($this->assetUrl('js/browse.js'));
$this->htmlElement('body')->appendAttribute('class', 'item resource browse');

$query = $this->params()->fromQuery();
$itemSetShow = isset($itemSet);
if ($itemSetShow):
    $this->htmlElement('body')->appendAttribute('class', 'item-set');
    $query['item_set_id'] = $itemSet->id();
endif;

$layoutSetting = $this->themeSetting('browse_layout');
$gridState = ($layoutSetting == 'togglegrid') ? 'disabled' : '';
$listState = ($layoutSetting == 'togglelist') ? 'disabled': '';
$isGrid = (!isset($layoutSetting) || strpos($layoutSetting, 'grid') !== false) ? true : false;
$headingTerm = $this->siteSetting('browse_heading_property_term');
$bodyTerm = $this->siteSetting('browse_body_property_term');
$bodyTruncate = $this->themeSetting('truncate_body_property');

$sortHeadings = [
    [
        'label' => $translate('Title'),
        'value' => 'dcterms:title'
    ],
    [
        'label' => $translate('Identifier'),
        'value' => 'dcterms:identifier'
    ],
    [
        'label' => $translate('Record Type'),
        'value' => 'ija:record_type'
    ],
    [
        'label' => $translate('Date'),
        'value' => 'dctersm:date'
    ],
    [
        'label' => $translate('Language'),
        'value' => 'dcterms:language'
    ],
];

function icon_map($record_type)
{
  switch($record_type) {
    case 'Books':
      echo 'fas fa-book-open';
      break;
    case 'Fragments':
      echo 'far fa-images';
      break;
    case 'Archival Materials':
      echo('fas fa-archive');
      break;
    case 'Video':
      echo('fab fa-youtube');
      break;
    case 'Other':
      echo('far fa-folder');
      break;
    case 'Documentation':
      echo('far fa-file-alt');
      break;
    case 'Photograph':
      echo('far fa-image');
      break;
    default:
      echo('far fa-file');
  }
}
?>
<!-- view/omeka/site/item/browse.phtml -->

<?php echo $this->searchFilters(); ?>

<div class="row mt-5 mb-5">
  <div class="col-md-4 col-sm-6">
    <?php echo $this->pagination(); ?>
  </div>
  <div class="col-md-4 col-sm-6 text-center">
    <?php echo $this->hyperlink($translate('Advanced search'), $this->url('site/resource', ['controller' => 'item', 'action' => 'search'], ['query' => $query], true), ['class' => 'advanced-search']); ?>
  </div>
  <div class="col-md-4 col-sm-6">
    <?php echo $this->sortSelector($sortHeadings); ?>
  </div>
</div>

<?php $this->trigger('view.browse.before'); ?>

<div class="row mb-2">
  <?php foreach ($items as $item):?>
    <?php
      $heading = $headingTerm ? $item->value($headingTerm, ['default' => $translate('[Untitled]')]) : $item->displayTitle();
      $body = $bodyTerm ? $item->value($bodyTerm) : $item->displayDescription();
      $recordType = $item->value('ija:record_type');
    ?>
    <div class="col-md-6">
      <div class="card row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary">
            <i class="<?php echo icon_map($recordType); ?>"></i>
            <?php echo $recordType; ?>
          </strong>
          <h3 class="mb-0"><?php echo $heading; ?></h3>
          <div class="mb-1 text-muted">
            <?php if($item->value('dcterms:date')): ?>
              Date: <?php echo $item->value('dcterms:date'); ?>
            <?php endif; ?>
            <?php if($item->value('ija:ija_number')): ?>
              <?php if($item->value('dcterms:date')): ?>
                &middot;
              <?php endif; ?>
              IJA Number: <?php echo $item->value('ija:ija_number'); ?>
            <?php endif; ?>
            <?php if($item->value('dcterms:language')): ?>
              &middot;
              Language: <?php echo $item->value('dcterms:language'); ?>
            <?php endif; ?>
          </div>
          <p class="card-text mb-auto">
            <?php if($body): ?>
              <div class="description <?php echo ($bodyTruncate) ? $bodyTruncate : ''; ?>">
                <?php echo nl2br($escape($body)); ?>
              </div>
            <?php endif; ?>
          </p>
          <?php echo $item->link('View Item', null, ['class' => 'streched-link']); ?>
        </div>
        <div class="col-auto d-none d-lg-block">
          <?php if ($thumbnail = $this->thumbnail($item, 'medium')): ?>
            <?php echo $item->linkRaw($thumbnail, null, ['class' => 'img-thumbnail', 'width' => 200, 'height' => 250]); ?>
          <?php endif; ?>
        </div>
      </div>
    </div>

  <?php endforeach; ?>

  <?php echo $this->pagination(); ?>

</div>
