<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
// $this->headScript()->appendFile($this->assetUrl('js/browse.js'));
$this->htmlElement('body')->appendAttribute('class', 'item resource browse');

$query = $this->params()->fromQuery();
$itemSetShow = isset($itemSet);
if ($itemSetShow):
    $this->htmlElement('body')->appendAttribute('class', 'item-set');
    $query['item_set_id'] = $itemSet->id();
endif;

$layoutSetting = $this->themeSetting('browse_layout');
$gridState = ($layoutSetting == 'togglegrid') ? 'disabled' : '';
$listState = ($layoutSetting == 'togglelist') ? 'disabled': '';
$isGrid = (!isset($layoutSetting) || strpos($layoutSetting, 'grid') !== false) ? true : false;
$headingTerm = $this->siteSetting('browse_heading_property_term');
$bodyTerm = $this->siteSetting('browse_body_property_term');
$bodyTruncate = $this->themeSetting('truncate_body_property');

$sortHeadings = [
    [
        'label' => $translate('Title'),
        'value' => 'dcterms:title'
    ],
    [
        'label' => $translate('Identifier'),
        'value' => 'dcterms:identifier'
    ],
    [
        'label' => $translate('Class'),
        'value' => 'resource_class_label'
    ],
    [
        'label' => $translate('Created'),
        'value' => 'created'
    ],
];
?>

<?php echo $this->searchFilters(); ?>
<?php echo $this->pagination(); ?>

<?php $this->trigger('view.browse.before'); ?>

<div class="album py-5">
  <div class="container">
    <div class="row row-cols-1 ro-cols-sm-2 row-cols-md-3 g-3">
      <?php foreach ($items as $item):?>
        <?php
          $heading = $headingTerm ? $item->value($headingTerm, ['default' => $translate('[Untitled]')]) : $item->displayTitle();
          $body = $bodyTerm ? $item->value($bodyTerm) : $item->displayDescription();
        ?>
        <div class="card shadow-sm">
          <div class="card-body">
            <?php if ($thumbnail = $this->thumbnail($item, 'medium')): ?>
              <?php echo $item->linkRaw($thumbnail, null, ['class' => 'bd-placeholder-img card-img-top']); ?>
            <?php endif; ?>
            <div class="card-body">
              <p class="card-text">
                <?php echo nl2br($escape($body)); ?>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <!-- TODO: link to item or remove -->
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                </div>
              </div>
            </div>
          </div>
        </div>

      <?php endforeach; ?>
    </div>
  </div>

  <?php echo $this->pagination(); ?>

</div>
