<?php
$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'items search');
?>
<!-- view/omeka/site/item/search.phtml -->
<h2><?php echo $translate('Advanced item search'); ?></h2>

<form id="advanced-search" method="get" action="<?php echo $this->escapeHtml($this->url(null, ['action' => 'browse'], true)); ?>">
  <?php echo $this->partial(
      'common/advanced-search',
      ['query' => $this->params()->fromQuery(), 'resourceType' => 'item']
  ); ?>

  <div id="page-actions" class="mt-4">
      <input class="btn btn-primary" type="submit" name="submit" value="<?php echo $this->escapeHtml($translate('Search')); ?>">
  </div>
</form>
