<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$labelInfo = $this->setting('property_label_information');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
// TODO refactor into shared functions
function icon_map($record_type)
{
  switch($record_type) {
    case 'Books':
      echo 'fas fa-book-open';
      break;
    case 'Fragments':
      echo 'far fa-images';
      break;
    case 'Archival Materials':
      echo('fas fa-archive');
      break;
    case 'Video':
      echo('fab fa-youtube');
      break;
    case 'Other':
      echo('far fa-folder');
      break;
    default:
      echo('far fa-file');
  }}
?>
<!-- view/omeka/site/item/show.phtml -->

<div class="row title-bar">
  <div class="col-1">
    <i class="<?php echo icon_map($item->value('ija:record_type'));?> fa-5x"></i>
  </div>
  <div class="col px-4">
    <?php if($item->value('ija:ija_number')): ?>
    <span class="small text-muted">IJA Number: <?php echo $item->value('ija:ija_number'); ?></span>
    <?php endif; ?>
    <?php echo $this->pageTitle($item->displayTitle(), 1); ?>
    <?php if($item->value('dcterms:alternative')): ?>
      <h2 class="transliteration"><?php echo $item->value('dcterms:alternative'); ?></h2>
    <?php endif; ?>
  </div>

  <p class="lead mb-4 mt-4">
    <?php echo $item->value('dcterms:description'); ?>
  </p>
</div>

<?php $this->trigger('view.show.after'); ?>

<div id="ija_metadata">
  <?php echo $item->displayValues(); ?>
</div>


<?php
   $page = $this->params()->fromQuery('page', 1);
   $property = $this->params()->fromQuery('property');
   $subjectValues = $item->displaySubjectValues($page, 25, $property);
?>
<?php if ($subjectValues): ?>
<div id="item-linked">
   <h3><?php echo $translate('Linked resources'); ?></h3>
   <?php echo $subjectValues; ?>
</div>
<?php endif; ?>
