<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$labelInfo = $this->setting('property_label_information');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();

// TODO refactor into shared functions
function icon_map($record_type)
{
  switch($record_type) {
    case 'Books':
      echo 'fas fa-book-open';
      break;
    case 'Fragments':
      echo 'far fa-images';
      break;
    case 'Archival Materials':
      echo('fas fa-archive');
      break;
    case 'Video':
      echo('fab fa-youtube');
      break;
    case 'Other':
      echo('far fa-folder');
      break;
    case 'Photograph':
      echo('far fa-image');
      break;
    default:
      echo('far fa-file');
  }}
?>
<!-- view/omeka/site/item/show.phtml -->

<div class="row title-bar auto">
  <div class="col-1">
    <i class="<?php echo icon_map($item->value('ija:record_type'));?> fa-5x"></i>
  </div>
  <div class="col-11 px-4">
    <?php if($item->value('ija:ija_number')): ?>
    <span class="small text-muted">IJA Number: <?php echo $item->value('ija:ija_number'); ?></span>
    <?php endif; ?>
    <?php echo $this->pageTitle($item->displayTitle(), 1); ?>
    <?php if($item->value('dcterms:alternative')): ?>
      <h2 class="transliteration"><?php echo $item->value('dcterms:alternative'); ?></h2>
    <?php endif; ?>
  </div>

  <p class="lead mb-4 mt-4">
    <?php echo $item->value('dcterms:description'); ?>
  </p>
</div>

<div class="row">
    <?php if($item->value('ija:record_type') == 'Video'): ?>
      <h2>View</h2>
      <?php foreach ($itemMedia as $media): ?>
        <div class="ratio ratio-16x9">
          <?php echo $media->render(['width' => '100%', 'height' => '100%']); ?>
        </div>
      <?php endforeach; ?>
    <?php else: ?>
      <h2>Preview</h2>
      <div class="col-md-10 col-sm-12">
      <?php $this->trigger('view.show.after'); ?>
      </div>
      <div class="col-md-2 col-sm-12">
        <?php if (!$embedMedia && $itemMedia): ?>
        <div class="media-list">
            <?php foreach ($itemMedia as $media): ?>
              here
                <?php
                  // TODO: see if there's an 'official' way to filter media files
                  if( mb_strpos($media->linkPretty(), '.pdf') ) {
                    // echo image_decorator($media, 'Download Full Text');
                    $thumb = $media->thumbnailUrl('medium');
                    echo '<a href="' . $media->originalUrl() . '">
                      <img class="img-thumbnail" src="' . $thumb . '" alt="' . $media->displayTitle() . '" /> <span  class="btn btn-outline-secondary">Download Full Text</span>
                    </a>';
                  }
                ?>
            <?php endforeach; ?>
        </div>
        <?php endif; ?>
      </div>
    <?php endif; ?>
</div>


<div id="ija_metadata">
  <?php echo $item->displayValues(); ?>
</div>

<?php if ($embedMedia && $itemMedia): ?>
<div class="media-embeds">
  media-embeds
<?php foreach ($itemMedia as $media):
    echo $media->render();
endforeach;
?>
</div>
<?php endif; ?>
<!-- <?php if (!$embedMedia && $itemMedia): ?>
<div class="media-list">
    <?php foreach ($itemMedia as $media): ?>
      <?php echo $item->value('ija:record_type'); ?>
      <div class="ratio ratio-16x9">
        <?php echo $media->render(['height' => '600', 'width' => '100%']); ?>
      </div>

        <?php //echo $media->linkPretty(); ?>
    <?php endforeach; ?>
</div>
<?php endif; ?> -->



<?php
   $page = $this->params()->fromQuery('page', 1);
   $property = $this->params()->fromQuery('property');
   $subjectValues = $item->displaySubjectValues($page, 25, $property);
?>
<?php if ($subjectValues): ?>
<div id="item-linked">
   <h3><?php echo $translate('Linked resources'); ?></h3>
   <?php echo $subjectValues; ?>
</div>
<?php endif; ?>
