<?php
$this->htmlElement('body')->appendAttribute('class', 'page ' . $page->slug());
$this->pageTitle($page->title(), 2);
$showPagePagination = $this->siteSetting('show_page_pagination', true);

$nav = $site->publicNav();
$container = $nav->getContainer();
$activePage = $nav->findActive($container);
?>
<!-- view/omeka/site/page/show -->
<?php if($activePage):?>
  <?php if ($activePage['depth'] !== 0): ?>
    <nav class="breadcrumbs"><?php echo $nav->breadcrumbs()->setPartial('common/bootstrap-breadcrumbs'); ?></nav>
  <?php endif; ?>

  <?php if ($this->displayNavigation && $activePage['page']->hasPages()): ?>
    <div class="bd-toc mt-4 my-md-9 ps-xl-3 mb-lg-5 text-muted">
      <nav id="TableOfContents">
        <?php echo $nav->menu()->setUlClass('')->renderSubMenu(); ?>
      </nav>
    </div>

  <?php endif; ?>
<?php endif; ?>

<?php $this->trigger('view.show.before'); ?>
<div class="blocks">
    <?php echo $this->content; ?>
</div>
<?php $this->trigger('view.show.after'); ?>
<?php if ($showPagePagination): ?>
<?php echo $this->sitePagePagination(); ?>
<?php endif; ?>
