<?php
$this->htmlElement('body')->appendAttribute('class', 'page ' . $page->slug());
$this->pageTitle($page->title(), 2);
$showPagePagination = $this->siteSetting('show_page_pagination', true);

$nav = $site->publicNav();
$container = $nav->getContainer();
$activePage = $nav->findActive($container);
?>
<?php if ($activePage): ?>
    <?php if ($activePage['depth'] !== 0): ?>
    <nav class="breadcrumbs"><?php echo $nav->breadcrumbs()->setPartial('common/bootstrap-breadcrumbs'); ?></nav>
    <?php endif; ?>
<?php endif; ?>

<div class="row">
    <?php if ($activePage): ?>
      <div class="col-md-3 col-sm-12 pt-3 light-bg">
        <nav class="sub-menu"><?php echo $nav->menu()->renderSubMenu(); ?></nav>
      </div>
    <?php endif; ?>

  <div class="col">
    <?php $this->trigger('view.show.before'); ?>
    <div class="blocks">
        <?php echo $this->content; ?>
    </div>
    <?php $this->trigger('view.show.after'); ?>
    <?php if ($showPagePagination): ?>
    <?php echo $this->sitePagePagination(); ?>
    <?php endif; ?>
  </div>

</div>
