<?php
$translate = $this->plugin('translate');
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
// $this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Source+Code+Pro|Lato:400,400italic,700,700italic');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
// $this->headLink()->appendStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
// $this->headLink()->appendStylesheet($this->assetUrl('css/style.css', 'Omeka'));
$this->headLink()->appendStylesheet($this->assetUrl('css/custom-bootstrap.css'));
$this->headLink()->appendStylesheet($this->assetUrl('css/main.css'));
// $this->headLink()->appendStylesheet('https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css',
//   '',
//   [
//     'integrity' => 'sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC',
//     'crossorigin' => 'anonymous'
//   ]
// );
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->appendFile(
  'https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js',
  'text/javascript',
  [
    'integrity' => "sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM",
    'crossorigin' => 'anonymous'
  ]
);

$this->headScript()->appendFile('https://kit.fontawesome.com/ca0736de6c.js', 'text/javascript', ['crossorigin' => "anonymous"]);

$this->trigger('view.layout');
$userBar = $this->userBar();

// $favicon = array(
//   'rel' => 'shortcut',
//   'href' => $this->assetUrl('favicon.ico')
// );
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html')->setAttribute('lang', $this->lang()); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <?php echo $userBar; ?>
        <div class="py-3">
          <header>
            <nav class="navbar navbar-expand-lg navbar-light">
              <div class="container">
                <a href="<?php echo $site->url(); ?>" class="navbar-brand">
                <?php if ($logoContent = $this->themeSettingAssetUrl('logo')): ?>
                <img class="ija-logo" width="80px" width="80px" alt="ija-logo" role="presentation" src="<?php echo $logoContent; ?>" />
                <?php else: ?>
                  <?php echo $this->pageTitle($site->title()); ?>
                <?php endif; ?>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                      <?php echo $site->publicNav()->menu()->setUlClass('navbar-nav me-auto mb-2 mb-lg-0')->setPartial('common/bootstrap-navigation.phtml'); ?>
                </div>
              </div>
            </nav>
        </div>

        <main>
          <div id="content" class="container" role="main">
              <?php echo $this->messages(); ?>
              <?php echo $this->content; ?>
          </div>
        </main>

        <footer class="mb-footer py-5 mt-5 bg-light">

          <div class="container py-5">
            <div class="row">
              <div class="col-lg-3">
                <span class="fs-5">Iraqi Jewish Archive</span>
                <ul class="list-unstyled small text-muted">
                  <li class="mb-2"><a href="https://www.clir.org/about/privacy/">Privacy Policy</a></li>
                  <li class="mb-2"><a href="https://www.clir.org">CLIR</a></li>
                  <li class="mb-2">
                    <?php if ($footerContent = $this->themeSetting('footer')): ?>
                      <?php echo $footerContent; ?>
                    <?php else: ?>
                      <?php echo $this->translate('Powered by Omeka S'); ?>
                    <?php endif; ?>
                  </li>
                </ul>
                <div class="social-links mt-3">
                    <a class="twitter" href="#"><i class="fa fa-twitter"></i></a>
                    <a class="facebook" href="#"><i class="fa fa-facebook"></i></a>
                    <a class="instagram" href="#"><i class="fa fa-instagram"></i></a>
                    <a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a>
                </div>
              </div>
              <div class="col-lg-3">
                <span class="fs-5">Sponsors</span>
                <ul class="list-unstyled small text-muted">
                    <li class="mb-2"><a href="https://www.clir.org/about/privacy/">Privacy Policy</a></li>
                </ul>
              </div>
            </div>
          </div>
        </footer>
    </body>
</html>
